---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: hetznercloud
platforms:
  - name: instance-0-debian
    server_type: cx11
    image: debian-10
    groups:
      - vpc_1
  - name: instance-1-debian
    server_type: cx11
    image: debian-10
    groups:
      - vpc_1

provisioner:
  name: ansible
  # This helps with create-debug
  log: true
  inventory:
    host_vars:
      instance-0-debian:
        cjdns_host_config:
          ipv6: "::0"
          key: "testKey"
      instance-1-debian:
        cjdns_host_config:
          ipv6: "::1"
          key: "testKey1"

verifier:
  name: ansible
